sql:
  host:
  port:
  database:
  username:
  password:

settings:
  startingbalance: 1000

  shop:
    maxitems: 9
    maxchests: 5
    maxdistance: 48
    maxprice: 100000

    bannedpreviewitems:
      - "minecraft:written_book"
      - "minecraft:writable_book"