sql:
  host:
  port:
  database:
  username:
  password:

settings:
  startingbalance: 1000

  shop:
    maxitems: 9

    bannedpreviewitems:
      - "minecraft:written_book"
      - "minecraft:writable_book"